#!/bin/bash

ERROR=0

HELPER_PATH="/Applications/IPSecuritas.app/Contents/Library/LaunchServices/com.lobotomo.IPSecuritasDaemon"

if [[ -f "$HELPER_PATH" ]]; then

	# create the target directory if needed
	if [[ ! -d "/Library/PrivilegedHelperTools" ]]; then
		/bin/mkdir -p "/Library/PrivilegedHelperTools"
		/bin/chmod 755 "/Library/PrivilegedHelperTools"
		/usr/sbin/chown -R root:wheel "/Library/PrivilegedHelperTools"
	fi
	
	# move the privileged helper into place
	/bin/cp -f "$HELPER_PATH" "/Library/PrivilegedHelperTools"
	
	if [[ $? -eq 0 ]]; then
		/bin/chmod 755 "/Library/PrivilegedHelperTools/com.lobotomo.IPSecuritasDaemon"

		# create the launchd plist
		MYPLIST="/Library/LaunchDaemons/com.lobotomo.IPSecuritasDaemon.plist"
	
		/usr/libexec/PlistBuddy -c 'add KeepAlive bool true' ${MYPLIST}
        /usr/libexec/PlistBuddy -c 'add Label string com.lobotomo.IPSecuritasDaemon' ${MYPLIST}
        /usr/libexec/PlistBuddy -c 'add Program string /Library/PrivilegedHelperTools/com.lobotomo.IPSecuritasDaemon' ${MYPLIST}
        /usr/libexec/PlistBuddy -c 'add RunAtLoad bool true' ${MYPLIST}
        /usr/libexec/PlistBuddy -c 'add ProgramArguments array' ${MYPLIST}
        /usr/libexec/PlistBuddy -c 'add :ProgramArguments: string /Library/PrivilegedHelperTools/com.lobotomo.IPSecuritasDaemon' ${MYPLIST}

		/bin/chmod 644 "$MYPLIST"
		
		# load the launchd plist
	    /bin/launchctl load -wF "$MYPLIST"

	else
		ERROR=1
	fi
else
	ERROR=1
fi

exit $ERROR