#!/bin/sh

nbipsec=$(echo $(ps aux |grep "racoon\-ipsecuritas" |grep -v grep |wc -l))

if [ $nbipsec -eq 0 ]
then 

  /usr/bin/killall com.lobotomo.IPSecuritasMenu
  /usr/bin/killall IPSecuritas.app

  # unload the launchd plist only if installing on the boot volume
  # unload the launchd plist only if installing on the boot volume
  /bin/launchctl unload "/Library/LaunchDaemons/com.lobotomo.IPSecuritasDaemon.plist"
  /usr/bin/killall /Library/PrivilegedHelperTools/com.lobotomo.IPSecuritasDaemon

  /bin/rm -rf "/Library/LaunchDaemons/com.lobotomo.IPSecuritasDaemon.plist" \
            "/Library/PrivilegedHelperTools/com.lobotomo.IPSecuritasDaemon"


  /usr/sbin/kextcache -clear-staging
  exit 0
else
  exit 1
fi

