#!/bin/sh

nbipsec=$(echo $(ps aux |grep "racoon\-ipsecuritas" |grep -v grep |wc -l))

if [ $nbipsec -eq 0 ]
then 

  /usr/bin/killall com.lobotomo.IPSecuritasMenu
  /usr/bin/killall IPSecuritas.app

  # unload the launchd plist only if installing on the boot volume
  # unload the launchd plist only if installing on the boot volume
  if [[ "$3" = "/" ]]; then
	/bin/launchctl unload "/Library/LaunchDaemons/com.lobotomo.IPSecuritasDaemon.plist"
        /usr/bin/killall /Library/PrivilegedHelperTools/com.lobotomo.IPSecuritasDaemon
  fi

  /bin/rm -rf "$3/Library/LaunchDaemons/com.lobotomo.IPSecuritasDaemon.plist" \
            "$3/Library/PrivilegedHelperTools/com.lobotomo.IPSecuritasDaemon"

  exit 0
else
  exit 1
fi

